
export const fullTestSubmitScore = {
    FULLTEST_SUBMITSCORE_LOADING : 'FULLTEST_SUBMITSCORE_LOADING',
    FULLTEST_SUBMITSCORE_SUCCESS : 'FULLTEST_SUBMITSCORE_SUCCESS',
    FULLTEST_SUBMITSCORE_FAILURE : 'FULLTEST_SUBMITSCORE_FAILURE',
    FULL_TEST_QUESTIONS_RESULT : 'FULL_TEST_QUESTIONS_RESULT'
}