
export const fullTests = {
    FULLTEST_QUESTIONS_LOADING : 'FULLTEST_QUESTIONS_LOADING',
    FULLTEST_QUESTIONS_SUCCESS : 'FULLTEST_QUESTIONS_SUCCESS',
    FULLTEST_QUESTIONS_FAILURE : 'FULLTEST_QUESTIONS_FAILURE'
}