
export const modal = {
    MODAL_QUESTIONS_LOADING : 'MODAL_QUESTIONS_LOADING',
    MODAL_QUESTIONS_SUCCESS : 'MODAL_QUESTIONS_SUCCESS',
    MODAL_QUESTIONS_FAILURE : 'MODAL_QUESTIONS_FAILURE',

    MODAL_LIST_LOADING : 'MODAL_LIST_LOADING',
    MODAL_LIST_SUCCESS : 'MODAL_LIST_SUCCESS',
    MODAL_LIST_FAILURE : 'MODAL_LIST_FAILURE',
}